language: C

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - texinfo

install:
  - wget https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
  - unzip -q android-ndk-r12b-linux-x86_64.zip
  - export ANDROID_NDK=$(pwd)/android-ndk-r12b

script:
  - make
