language: generic

os:
  - osx
# https://github.com/travis-ci/cpython-builder/pull/3 should be resolved for better Python support on macOS

osx_image: xcode9.3

sudo: false

branches:
  only:
    - master
    - /^test-.*$/

env:
  global:
    - NDK_VER=r17-beta2
    - PYBUILD_SRC=$HOME/pybuild-src

  matrix:
    - ANDROID_PLATFORM=arm
    - ANDROID_PLATFORM=arm64
    - ANDROID_PLATFORM=x86
    - ANDROID_PLATFORM=x86_64

install:
  - |
      export COLUMNS=80
      curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
      chmod +x ./macports-ci
      ./macports-ci install
  - PATH="/opt/local/bin:$PATH"
  - |
      git clone https://gitlab.com/yan12125/macports-overlay
      ./macports-ci localports $(pwd)/macports-overlay
  - |
      sudo port -N install python38  # trace mode (-t) seems not working
      python3.8 -m ensurepip --user
      python3.8 -m pip install --user requests python-gnupg
  - |
      pushd $HOME
      "$TRAVIS_BUILD_DIR"/devscripts/prepare-ndk.sh $NDK_VER
      popd
  - export ANDROID_NDK=$HOME/android-ndk-$NDK_VER
  - gpg --debug ipc --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys $(python3.8 -m pybuild.pgp_keys)
  # bintray uses GeoTrust's cert ... not trusted by Travis CI's images?
  - sed -i .bak -e 's#use_bintray = True#use_bintray = False#' pybuild/env.py

script:
  - python3.8 -m pybuild.clean
  - make
  - make test
