language: generic

os:
  - linux

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - texinfo

env:
  global:
    - NDK_VER=r14b
  matrix:
    - ANDROID_PLATFORM=arm
    - ANDROID_PLATFORM=arm64
    - ANDROID_PLATFORM=mips
    - ANDROID_PLATFORM=mips64
    - ANDROID_PLATFORM=x86
    - ANDROID_PLATFORM=x86_64

install:
  - source ./travis/install-python-nightly.sh
  - |
      pushd $HOME
      HOST_OS="$(uname | tr 'A-Z' 'a-z')"
      wget https://dl.google.com/android/repository/android-ndk-$NDK_VER-$HOST_OS-x86_64.zip
      unzip -q android-ndk-$NDK_VER-$HOST_OS-x86_64.zip
      popd
  - export ANDROID_NDK=$HOME/android-ndk-$NDK_VER

script:
  - make
  - make test
