language: python

python: nightly

os:
  - linux
# https://github.com/travis-ci/cpython-builder/pull/3 should be resolved for Mac support

sudo: false
dist: trusty

addons:
  apt:
    packages:
      - texinfo

cache:
  directories:
  - $HOME/pybuild-src

branches:
  only:
    - master
    - /^test-.*$/

env:
  global:
    - PYBUILD_SRC=$HOME/pybuild-src
  matrix:
    - ANDROID_PLATFORM=arm
    - ANDROID_PLATFORM=arm64
    - ANDROID_PLATFORM=mips
    - ANDROID_PLATFORM=mips64
    - ANDROID_PLATFORM=x86
    - ANDROID_PLATFORM=x86_64

install:
  - |
      pushd $HOME
      HOST_OS="$(uname | tr 'A-Z' 'a-z')"
      curl -v -L "https://www.dropbox.com/s/1ml9eho7c3i11rd/ndk-binutils-2.27.tar.bz2?dl=1" > ndk-binutils-2.27.tar.bz2
      tar xf ndk-binutils-2.27.tar.bz2
      popd
  - export ANDROID_NDK=$HOME/ndk-binutils-2.27

script:
  - python -m pybuild.clean --package :COMMIT_MARKER,python
  - make
  - make test
