language: python

python: nightly

os:
  - linux
# https://github.com/travis-ci/cpython-builder/pull/3 should be resolved for Mac support

sudo: false
dist: trusty

addons:
  apt:
    packages:
      - texinfo

cache:
  directories:
  - $HOME/pybuild-src

branches:
  only:
    - master
    - /^test-.*$/

env:
  global:
    - NDK_VER=r15c
    - PYBUILD_SRC=$HOME/pybuild-src
  matrix:
    - ANDROID_PLATFORM=arm
    - ANDROID_PLATFORM=arm64
    - ANDROID_PLATFORM=mips
    - ANDROID_PLATFORM=mips64
    - ANDROID_PLATFORM=x86
    - ANDROID_PLATFORM=x86_64

install:
  - |
      pushd $HOME
      HOST_OS="$(uname | tr 'A-Z' 'a-z')"
      wget https://dl.google.com/android/repository/android-ndk-$NDK_VER-$HOST_OS-x86_64.zip
      unzip -q android-ndk-$NDK_VER-$HOST_OS-x86_64.zip
      popd
  - export ANDROID_NDK=$HOME/android-ndk-$NDK_VER

script:
  - python -m pybuild.clean --package :COMMIT_MARKER,python
  - make
  - make test
