language: python

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - texinfo

python:
  - "nightly"

env:
  - ANDROID_PLATFORM=arm
  - ANDROID_PLATFORM=arm64
  - ANDROID_PLATFORM=mips
  - ANDROID_PLATFORM=mips64
  - ANDROID_PLATFORM=x86
  - ANDROID_PLATFORM=x86_64

install:
  - cat travis/hgrc >> ~/.hgrc
  - |
      pushd $HOME
      wget https://dl.google.com/android/repository/android-ndk-r14-beta1-linux-x86_64.zip
      unzip -q android-ndk-r14-beta1-linux-x86_64.zip
      popd
  - export ANDROID_NDK=$HOME/android-ndk-r14-beta1

script:
  - make

matrix:
  allow_failures:
    - env: ANDROID_PLATFORM=mips
