language: generic

os:
  - osx
# https://github.com/travis-ci/cpython-builder/pull/3 should be resolved for better Python support on macOS

osx_image: xcode9.3

sudo: false

branches:
  only:
    - master
    - /^test-.*$/

env:
  global:
    - PYBUILD_SRC=$HOME/pybuild-src

  matrix:
    - ANDROID_PLATFORM=arm
    - ANDROID_PLATFORM=arm64
    - ANDROID_PLATFORM=x86
    - ANDROID_PLATFORM=x86_64

install:
  - |
      export COLUMNS=80
      curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
      chmod +x ./macports-ci
      ./macports-ci install
  - PATH="/opt/local/bin:$PATH"
  - |
      git clone https://gitlab.com/yan12125/macports-overlay
      ./macports-ci localports $(pwd)/macports-overlay
  - |
      cat $(pwd)/devscripts/macports-archive-sites.conf | sudo tee -a /opt/local/etc/macports/archive_sites.conf
      echo $(pwd)/devscripts/macports-chyen-pubkey.pem | sudo tee -a /opt/local/etc/macports/pubkeys.conf
  - |
      sudo port -Nb install python38
      python3.8 -m ensurepip --user
      python3.8 -m pip install --user requests python-gnupg
  - |
      pushd $HOME
      "$TRAVIS_BUILD_DIR/devscripts/prepare-ndk.sh"
      popd
  - export ANDROID_NDK=$HOME/android-ndk
  - "$TRAVIS_BUILD_DIR/devscripts/import_pgp_keys.sh"

script:
  - python3.8 -m pybuild.clean
  - make
  - make test
