language: C

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - texinfo

install:
  - cat travis/hgrc >> ~/.hgrc
  - hg clone https://hg.python.org/cpython/ && pushd cpython && ./configure --prefix=$HOME/usr && make && make install && popd
  - export PATH=$PATH:$HOME/usr/bin
  - wget https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
  - unzip -q android-ndk-r12b-linux-x86_64.zip
  - export ANDROID_NDK=$(pwd)/android-ndk-r12b

script:
  - make
