language: generic

os:
  - osx
# https://github.com/travis-ci/cpython-builder/pull/3 should be resolved for better Python support on macOS

osx_image: xcode10

sudo: false

branches:
  only:
    - master
    - /^test-.*$/

env:
  global:
    - PYTHON=python3.8
    - PYBUILD_SRC=$HOME/pybuild-src

  matrix:
    - ANDROID_PLATFORM=arm ANDROID_API_LEVEL=21
    - ANDROID_PLATFORM=arm64 ANDROID_API_LEVEL=21
    - ANDROID_PLATFORM=x86 ANDROID_API_LEVEL=21
    - ANDROID_PLATFORM=x86_64 ANDROID_API_LEVEL=21
    - ANDROID_PLATFORM=arm ANDROID_API_LEVEL=27
    - ANDROID_PLATFORM=arm64 ANDROID_API_LEVEL=27
    - ANDROID_PLATFORM=x86 ANDROID_API_LEVEL=27
    - ANDROID_PLATFORM=x86_64 ANDROID_API_LEVEL=27

install:
  - |
      curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
      source ./macports-ci install
  - PATH="/opt/local/libexec/gnubin:/opt/local/bin:$PATH"
  - |
      sudo port -Nb install python38-devel curl-ca-bundle gnutar gsed
      $PYTHON -m ensurepip --user
      $PYTHON -m pip install --user python-gnupg
  - |
      pushd $HOME
      "$TRAVIS_BUILD_DIR/devscripts/prepare-ndk.sh"
      popd
  - export ANDROID_NDK=$HOME/android-ndk
  - "$TRAVIS_BUILD_DIR/devscripts/import_pgp_keys.sh"

script:
  - $PYTHON -m pybuild.clean
  - make
  - make test
